[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false)
Write-Output '====================================='
Write-Output '      王总微信数字分身 V0.2.1'
Write-Output '====================================='
Write-Output '1. 安装并首次配置'
Write-Output '2. 运行诊断'
Write-Output '3. 启动影子模式'
Write-Output '4. 启动低风险自动回复'
Write-Output '5. 启动受控全自动'
Write-Output '6. 打开本地审核台'
Write-Output '7. 添加联系人'
Write-Output '8. 暂停处理'
Write-Output '9. 恢复处理'
Write-Output 'A. 编辑配置'
Write-Output 'B. 训练我的口气'
Write-Output 'C. 启动已授权的全部聊天接管'
Write-Output '0. 退出'
Write-Output ''
